# Generated by Django 3.1.7 on 2021-02-21 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_cust', models.CharField(max_length=50)),
                ('to_cust', models.CharField(max_length=50)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
